# Generated by Django 3.2 on 2023-01-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_form_builder', '0002_alter_form_cmsplugin_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='tag_type',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='tag_type',
        ),
    ]
